name: speed_tracker
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Work with file
  csv: 5.0.2
  file_picker: 5.3.2
  intl: 0.18.0
  path_provider: 2.0.15
  pdf: 3.10.4

  # UI
  fl_chart: 0.63.0
  google_fonts: 5.1.0
  
  #State management
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  equatable: 2.0.5

  
  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.1

flutter:

  uses-material-design: true

  assets:
    - assets/pictures/
  
  fonts:
     - family: Rubik
       fonts:
         - asset: assets/fonts/Rubik-Bold.ttf
         - asset: assets/fonts/Rubik-Light.ttf
         - asset: assets/fonts/Rubik-Medium.ttf
         - asset: assets/fonts/Rubik-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700